apiVersion: v1
kind: Deployment
metadata:
  name: memcached
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
        - name: memcached
          image: osp-on-ocp/rhel-binary-memcached
          env:
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ALWAYS
          ports:
            - containerPort: 11211
              name: memcached
          volumeMounts:
            - name: kolla-config
              mountPath: /var/lib/kolla/config_files/
      volumes:
        - name: kolla-config
          configMap:
            name: memcached-kolla-config
