apiVersion: v1
kind: Template
metadata:
  name: openstack-memcached-template 
  annotations:
    description: "Memcached" 
    iconClass: "icon-redis" 
    tags: "openstack,memcached"
objects:   
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${NAME}
    label:
      name: ${NAME}
    spec:
      ports:
      - port: 11211
        protocol: TCP
        targetPort: 11211
      selector:
        name: ${NAME}
  - kind: Pod
    apiVersion: v1
    metadata:
      name: ${NAME}
    label:
      name: ${NAME}
    spec:
      containers:
      - name: "memcached"
        image: docker.io/memcached
        ports:
        - containerPort: 11211
          protocol: TCP
parameters:  
  - 
    description: "memcached"
    name: NAME
    value: memcached
    required: true
