apiVersion: v1
kind: Template
metadata:
  name: openstack-mariadb-template 
  annotations:
    description: "MariaDB" 
    iconClass: "icon-redis" 
    tags: "openstack,mariadb"
objects:   
  - apiVersion: apps/v1beta1
    kind: StatefulSet
    spec:
      serviceName: mariadb
      replicas: 1
      template:
        metadata:
          labels:
            service: mariadb
          annotations:
            pod.beta.kubernetes.io/init-containers: '[          
              {
                 "name": "dependencies",
                 "image": "172.30.202.25:5000/osp-dev/rhel-binary-mariadb",
                 "imagePullPolicy": "IfNotPresent",
                 "env": [
                   {
                     "name": "TZ",
                     "value": "UTC"
                   },
                   {
                     "name": "DEPENDENCY_JOBS",
                     "value": "mariadb-init-element"
                   },
                   {
                     "name": "NAMESPACE",
                     "value": "NAMESPACE"
                   }
                 ]
              }
            ]'
        spec:
          nodeSelector:
              kolla_controller: "true"
          containers:
            - image: "172.30.202.25:5000/osp-dev/rhel-binary-mariadb"
              imagePullPolicy: "IfNotPresent"
              name: main
              lifecycle:
                preStop:
                  exec:
                    command: ["mysqladmin -u root -p$DATABASE_PASSWORD shutdown"]
              volumeMounts:            
                - mountPath: /var/log/kolla/
                  name: kolla-logs
                - mountPath: /var/lib/kolla/config_files
                  name: kolla-config
                - mountPath: /etc/my.cnf.d
                  name: mariadb-config
                - mountPath: /var/lib/mysql
                  name: mariadb-persistent-storage
              env:            
                - name: TZ
                  value: UTC
                - name: KOLLA_CONFIG_STRATEGY
                  value: COPY_ONCE
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: database-password
                      key: password
              ports:
                - containerPort: 3306
                  name: "mariadb"        
          volumes:        
            - name: kolla-logs
              emptyDir: {}
            - name: kolla-config
              configMap:
                name: mariadb
            - name: mariadb-persistent-storage
              persistentVolumeClaim:
                claimName: mariadb
    metadata:
       name: mariadb

  - apiVersion: batch/v1
    kind: Job
    spec:
      template:
        spec:
          nodeSelector:
              kolla_controller: "true"
          containers:
            - image: "172.30.202.25:5000/osp-dev/rhel-binary-mariadb"
              imagePullPolicy: "IfNotPresent"
              name: main
              volumeMounts:            
                - mountPath: /var/log/kolla/
                  name: kolla-logs
                - mountPath: /etc/my.cnf.d
                  name: mariadb-config
                - mountPath: /var/lib/kolla/config_files
                  name: kolla-config
                - mountPath: /var/lib/mysql
                  name: mariadb-persistent-storage
              env:            
                - name: TZ
                  value: UTC
                - name: KOLLA_CONFIG_STRATEGY
                  value: COPY_ONCE
                - name: DB_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: database-password
                      key: password
          volumes:        
            - name: kolla-logs
              emptyDir: {}
            - name: mariadb-config
              configMap:
                name: mariadb-kolla-config
                items:
                  - key: server-cnf
                    path: server.cnf
            - name: kolla-config
              configMap:
                name: mariadb-kolla-config
                items:
                  - key: kolla-config
                    path: config.json
            - name: mariadb-persistent-storage
              persistentVolumeClaim:
                claimName: mariadb
          restartPolicy: OnFailure
    metadata:
      name: mariadb-init-element

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: mariadb-kolla-config
    data:
      kolla-config: |
        {
            "command": "/usr/bin/mysqld_safe",
            "config_files": []
        }
      server-cnf: |
        [mysqld]
        pid-file=/var/lib/mysql/mariadb.pid

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: mariadb
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1
    
  - apiVersion: v1
    kind: Service
    spec:
      ports:
        - port: 3306
          name: "mariadb"
      selector:
        service: "mariadb"
    metadata:
      name:  "mariadb"
